name: fairness_dev
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - jupyterlab=4.4.6
  - matplotlib=3.10.6
  - numpy=2.3.2
  - pandas=2.3.2
  - pytest=8.4.1
  - python=3.12
  - scikit-learn=1.7.1