name: fairness_demo
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.4.6
  - matplotlib=3.10.6
  - numpy=2.3.2
  - pandas=2.3.2
  - pip=25.2
  - python=3.12
  - scikit-learn=1.7.1
  - pip:
      - --index-url https://test.pypi.org/simple/
      - fairness==0.1.0
      